# Exercise 3: NumPy
a) Import numpy and create three numpy.arrays with 5 elements each.
You can use for example these:
[4 9 3.34 6 9.5]
[9.55 92.4 0.55 244 5]
[0 0 0 1 0]

b) Multiply the elements of the first two arrays with each other and look at the result.

c) Concatenate all three arrays to a 15 element long 1D array.

d) Stack the arrays from a) to a 3x5 matrix. Convert also to a 5x3 matrix. BONUS: Create a random 3D array.

e) Access the middle row, the middle column and the center element of the 2D matrix.

f) BONUS: Create an 5x5 array filled with zeros. Create a 3x3 array filled with ones. Add the second array of size 3x3 to the center of the first array. 

In [1]:
# a) Import numpy and create three numpy.arrays with 5 elements each.
# You can use for example these:
# [4 9 3.34 6 9.5]
# [9.55 92.4 0.55 244 5]
# [0 0 0 1 0]

import numpy as np
a = np.array([4, 9, 3.34, 6, 9.5])
b = np.array([9.55, 92.4, 0.55, 244, 5])
c = np.array([0, 0, 0, 1, 0])

In [2]:
# b) Multiply the elements of the first two arrays with each other and look at the result.

d = a * b
print(d)

[  38.2    831.6      1.837 1464.      47.5  ]


In [3]:
# c) Concatenate all three arrays to a 15 element long 1D array.

e = np.concatenate((a, b, c))
print(e)

[  4.     9.     3.34   6.     9.5    9.55  92.4    0.55 244.     5.
   0.     0.     0.     1.     0.  ]


In [ ]:
# d) Stack the arrays from a) to a 3x5 matrix. Convert also to a 5x3 matrix. BONUS: Create a random 3D array.
f = np.stack((a, b, c))
print(f)

[[  4.     9.     3.34   6.     9.5 ]
 [  9.55  92.4    0.55 244.     5.  ]
 [  0.     0.     0.     1.     0.  ]]


In [7]:
# and reshape it to 5x3
g = f.reshape(5, 3)
print(g)

[[  4.     9.     3.34]
 [  6.     9.5    9.55]
 [ 92.4    0.55 244.  ]
 [  5.     0.     0.  ]
 [  0.     1.     0.  ]]


In [11]:
# Create random 3D array
h = np.random.randint(10,size=(3, 4, 5))
print(h)

[[[6 8 4 4 0]
  [4 0 5 7 5]
  [7 0 7 6 9]
  [4 6 4 4 8]]

 [[2 9 3 6 7]
  [2 4 2 2 0]
  [8 6 0 6 5]
  [2 2 0 7 6]]

 [[4 0 1 4 8]
  [5 8 4 4 9]
  [2 0 5 1 2]
  [6 3 9 3 4]]]


In [12]:
# e) Access the middle row, the middle column and the center element of the 2D matrix.

middle_row = f[1]
print("Middle row:", middle_row)

middle_column = f[:, 1]
print("Middle column:", middle_column)

center_element = f[1, 1]
print("Center element:", center_element)

Middle row: [  9.55  92.4    0.55 244.     5.  ]
Middle column: [ 9.  92.4  0. ]
Center element: 92.4


In [14]:
# f) BONUS: Create an 5x5 array filled with zeros. Create a 3x3 array filled with ones.
# Add the second array of size 3x3 to the center of the first array. 

i = np.zeros((5, 5))
print("5x5 array filled with zeros:\n", i)

j = np.ones((3, 3))
print("3x3 array filled with ones:\n", j)

# Add the 3x3 array to the center of the 5x5 array
i[1:4, 1:4] = i[1:4, 1:4] + j
i

5x5 array filled with zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3x3 array filled with ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

**Disclaimer: This Solution was generated with the help of AI: Github Copilot!**